SELECTION-SCREEN: BEGIN OF LINE.
  "--- Radio button text.
  SELECTION-SCREEN:COMMENT (25) TEXT-001.
  "--- Radio button 1_label.
  SELECTION-SCREEN: POSITION 32.
  PARAMETERS: p_total RADIOBUTTON GROUP rb1 DEFAULT 'X'.
  SELECTION-SCREEN:COMMENT 34(8) TEXT-002 FOR FIELD p_total.
  "--- Radio button 2_label.
  PARAMETERS: p_inprs RADIOBUTTON GROUP rb1.
  SELECTION-SCREEN:COMMENT 45(8) TEXT-002 FOR FIELD p_inprs.
  "--- Radio button 3_label.
  PARAMETERS: p_compt RADIOBUTTON GROUP rb1.
  SELECTION-SCREEN:COMMENT 56(8) TEXT-002 FOR FIELD p_compt.
SELECTION-SCREEN: END OF LINE.
